# Generated by Django 4.0.2 on 2022-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('age', models.IntegerField()),
                ('info', models.TextField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
