# Generated by Django 4.0.2 on 2022-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
